# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Marius Millea
tagline:          'CosmicMar'
description:      'Cosmologist'
url:              http://cosmicmar.com
baseurl:          /

author:
  name:           'Marius Millea'
  # url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
