# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Marius Millea
tagline:          'CosmicMar'
description:      'Cosmologist'
url:              http://cosmicmar.com

author:
  name:           'Marius Millea'

paginate:         5
paginate_path:    "/posts/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

excerpt_separator: <!--more-->
